In [20]:
import numpy as np
from numpy import hstack
from numpy import insert
from keras.preprocessing.sequence import TimeseriesGenerator

In [32]:
X1 = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]],dtype=object)
X2 = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]],dtype=object)
y = np.array([[2,4,6,8,10,12,14,16,18,20],[2,4,6,8,10,12,14,16,18,20]],dtype=object)

X1 = np.concatenate((X1), axis=None)
X2 = np.concatenate((X2), axis=None)
y = np.concatenate((y), axis=None)

X1 = X1.reshape((len(X1), 1))
X2 = X2.reshape((len(X2), 1))
y = y.reshape((len(y), 1))
#print(y)


dataset = hstack((X1, X2))

#print(dataset)

generator = TimeseriesGenerator(dataset, y, length= 5, batch_size=1,stride=3)
for i in range(len(generator)):
    x, y = generator[i]
    print('%s => %s' % (x, y))


[[[1 1]
  [2 2]
  [3 3]
  [4 4]
  [5 5]]] => [[12]]
[[[4 4]
  [5 5]
  [6 6]
  [7 7]
  [8 8]]] => [[18]]
[[[7 7]
  [8 8]
  [9 9]
  [10 10]
  [11 11]]] => [[4]]
[[[10 10]
  [11 11]
  [12 12]
  [13 13]
  [14 14]]] => [[10]]
[[[13 13]
  [14 14]
  [15 15]
  [16 16]
  [17 17]]] => [[16]]


In [28]:
in_seq1 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
in_seq2 = np.array([15, 25, 35, 45, 55, 65, 75, 85, 95, 105])
out_seq = np.array([25, 45, 65, 85, 105, 125, 145, 165, 185, 205])
# reshape series
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))
# horizontally stack columns
dataset = hstack((in_seq1, in_seq2))
# shift the target sample by one step
out_seq = insert(out_seq, 0, 0)
# define generator
n_input = 1
generator = TimeseriesGenerator(dataset, out_seq, length=n_input, batch_size=1)
# print each sample
for i in range(len(generator)):
 x, y = generator[i]
 print('%s => %s' % (x, y))

ValueError: Data and targets have to be of same length. Data length is 10 while target length is 11